name: Run Automated Regression Testcases

on:

 workflow_dispatch:
  inputs:
    Branches:
         description: Select Branch for run
         default: 'main'
         required: true
         type: choice
         options:
         - main
         - MyStroyTest-SNDH369852
         - Story-Test-SNDH236541
         
    TestSuite:
         description: Select Test Suite for Execution
         default: 'TestRunner'
         required: true
         type: choice
         options:
         - TestRunner
         - TestSmokeRunner
         - TestRegressionRunner
 
jobs:
  build:
    runs-on: windows-latest
    steps:
     - name: Set up JDK 8
       uses: actions/checkout@v2
       with:
        java-version: '8'
        
     - name : Setup Maven
       uses : stCarolas/setup-maven@v.4.5
       with :
        maven-version: 3.8.2
       
     - name: Run Automated TestCases
       working-directory: ./apiautomation
       run: mvn clean -Dtest=${{github.event.inputs.TestSuite}} test
      
     - name: Upload Execution Report
       if : ${{always()}}
       uses: actions/upload-artifact@v3.1.2
       with:
        name: Please download excution report
        path: D:/a/APIAutomationPorject/APIAutomationPorject/apiautomation/target
