name: Run Automated Regression Testcases

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name : Setup Maven
      uses : stCarolas/setup-maven@v.4.5
      with :
       maven-version: 3.8.2
       
    - name: Run Automated TestCases
      working-directory: ./apiautomation
      run: mvn clean -Dtest=TestRunner test
      
    - name: Upload Execution Report
      if : ${{always()}}
      uses: actions/upload-artifact@v3.1.2
      with:
       name: Please download excution report
       path: D:/a/APIAutomationPorject/APIAutomationPorject/apiautomation/target
